---
openapi: 3.0.1
info:
  title: API
  version: 1.0
  description: Описание запросов
paths:
  "/api/client/session":
    get:
      summary: Получение текущего пользователя
      tags:
      - Пользователь - Сессия
      security:
      - Bearer: {}
      responses:
        '200':
          description: пользователя успешно получен
          content:
            application/json:
              examples:
                пользователя успешно получен:
                  value:
                    id: 83
                    avatar:
                    created_at: 2022-11-22 09:52:12 UTC
                    email: marquis@prosacco-mcclure.org
                    name: Shena Yost
                    updated_at: 2022-11-22 09:52:12 UTC
                  summary: пользователя успешно получен
    delete:
      summary: Удаление сессии
      tags:
      - Пользователь - Сессия
      security:
      - Bearer: {}
      responses:
        '200':
          description: сессия удалена
  "/api/experiences":
    get:
      summary: Получить список впечатлений
      tags:
      - Впечатления
      security:
      - Bearer: {}
      parameters:
      - name: search
        in: query
        required: false
        description: 'Поиск по полям: name'
        schema:
          type: string
      - name: page
        in: query
        required: false
        description: Номер нужной страници
      - name: items
        in: query
        required: false
        description: Кол-во элементов отображаемых на странице
      responses:
        '200':
          description: Список впечатлений получен
          content:
            application/json:
              examples:
                Список впечатлений получен:
                  value:
                  - id: 8
                    created_at: 2022-11-22 09:52:12 UTC
                    host:
                      id: 85
                      avatar:
                      created_at: 2022-11-22 09:52:12 UTC
                      email: angelyn@rau-kerluke.info
                      name: Floyd Block
                      updated_at: 2022-11-22 09:52:12 UTC
                    name: MyString
                    photos: []
                    price: MyString
                    rating: 1
                    updated_at: 2022-11-22 09:52:12 UTC
                    video:
                  summary: Список впечатлений получен
  "/api/registration":
    post:
      summary: Зарегистрироваться
      tags:
      - Регистрация
      parameters: []
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              examples:
                Пользователь создан:
                  value:
                    id: 87
                    avatar:
                    created_at: 2022-11-22 09:52:12 UTC
                    email: test@test.test
                    errors:
                      full_messages: []
                      messages: {}
                    name: Test
                    updated_at: 2022-11-22 09:52:12 UTC
                  summary: Пользователь создан
        '422':
          description: Ошибка при регистрации
          content:
            application/json:
              examples:
                Пользователь уже существует:
                  value:
                    error: User with this email already exists!
                  summary: Пользователь уже существует
                Ошибка при регистрации:
                  value:
                    id:
                    avatar:
                    created_at:
                    email:
                    errors:
                      full_messages:
                      - Email can't be blank
                      messages:
                        email:
                        - can't be blank
                    name: Test
                    updated_at:
                  summary: Ошибка при регистрации
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/registration"
  "/api/session":
    post:
      summary: Создать сессию
      tags:
      - Сессия
      parameters: []
      responses:
        '200':
          description: Сессия создана
          content:
            application/json:
              examples:
                Сессия создана:
                  value:
                    csrf: PLImDvSuG152kbKe37Td7TgqEHOk2IzU2GYWvS4QYpv7CtY+811JFGMG4eajFX7tdc81S6Ri8zAOBy/NTmZR0A==
                    access: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjkxOTcxMzIsInVzZXJfaWQiOjg5LCJ1aWQiOiIzY2FkMTQ0Ni0zNWY4LTRhNTgtOGNlMC1iNTc5YTRmZjczMTciLCJydWlkIjoiZjIyZWVhMzQtNDQ2ZC00MmY1LWI3N2UtOGVmNzE4N2I4ZGVjIn0.vKA_W8_P5RdpJK9dMc1JGcawlhBXZcjEuHbn6p7Bdk0
                    access_expires_at: '2022-11-23T12:52:12.000+03:00'
                    refresh: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NzE3NDA0NzgsInVzZXJfaWQiOjg5LCJ1aWQiOiJmMjJlZWEzNC00NDZkLTQyZjUtYjc3ZS04ZWY3MTg3YjhkZWMifQ.mudi-4KoNfp2iO7u0KHv-fvIwiwqln2oKbsIOsO3SOw
                    refresh_expires_at: '2022-12-22T23:21:18.000+03:00'
                  summary: Сессия создана
        '422':
          description: Неверный пароль
          content:
            application/json:
              examples:
                Неверный пароль:
                  value:
                    error: Invalid email or password!
                  summary: Неверный пароль
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth"
    put:
      summary: Обновить токен
      tags:
      - Сессия
      parameters:
      - in: header
        name: X-Refresh-Token
        required: true
        description: Рефрешь токен
        schema:
          type: string
      responses:
        '200':
          description: Токен сессии обновлен
          content:
            application/json:
              examples:
                Токен сессии обновлен:
                  value:
                    csrf: v4w0s7f5Alj2PGq095mkdFBHLQ1eKO4rPQ/BUTrkzbpwgJvg8WFipcRn0KV+D5oOozeNru9/ovx6WPixkvxktg==
                    access: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjkxOTcxMzIsInVzZXJfaWQiOjkxLCJ1aWQiOiI4Nzg1NGY1Ny1jYzNjLTQwMDctOTk1NS04MTdjMDY3ODI1ZjkifQ.EmP-oaJJoBkQ4X-P9BzK6bqUF_m9zB4sEaSzkPLeQT8
                    access_expires_at: '2022-11-23T12:52:12.000+03:00'
                  summary: Токен сессии обновлен
        '403':
          description: Срок действия рефреш токена истек
          content:
            application/json:
              examples:
                Срок действия рефреш токена истек:
                  value:
                    error: Session expired!
                  summary: Срок действия рефреш токена истек
  "/api/stays":
    get:
      summary: Получить список мест
      tags:
      - Места
      security:
      - Bearer: {}
      parameters:
      - name: search
        in: query
        required: false
        description: Поиск по полю name
        schema:
          type: string
      - name: page
        in: query
        required: false
        description: Номер нужной страници
      - name: items
        in: query
        required: false
        description: Кол-во элементов отображаемых на странице
      responses:
        '200':
          description: Список мест получен
          content:
            application/json:
              examples:
                Список мест получен:
                  value:
                  - id: 11
                    created_at: 2022-11-22 09:52:12 UTC
                    date_from: 2022-11-21 00:00:00 UTC
                    date_to: 2022-11-22 00:00:00 UTC
                    location: MyString
                    name: MyString
                    photos: []
                    price: MyString
                    rating:
                    updated_at: 2022-11-22 09:52:12 UTC
                  summary: Список мест получен
  "/api/stays/{id}":
    parameters:
    - name: id
      in: path
      required: true
      description: ID места
      schema:
        type: string
    get:
      summary: Получить место
      tags:
      - Места
      security:
      - Bearer: {}
      responses:
        '200':
          description: Место получено
          content:
            application/json:
              examples:
                Место получено:
                  value:
                    id: 12
                    created_at: 2022-11-22 09:52:12 UTC
                    date_from: 2022-11-21 00:00:00 UTC
                    date_to: 2022-11-22 00:00:00 UTC
                    host:
                      id: 95
                      avatar:
                      created_at: 2022-11-22 09:52:12 UTC
                      email: shanel@herzog.com
                      name: Salvador Mueller
                      updated_at: 2022-11-22 09:52:12 UTC
                    location: MyString
                    name: MyString
                    photos: []
                    price: MyString
                    rating:
                    updated_at: 2022-11-22 09:52:12 UTC
                  summary: Место получено
        '404':
          description: Место не найден
          content:
            application/json:
              examples:
                Место не найден:
                  value:
                    error: Stays not found!
                  summary: Место не найден
schemes:
- http
- https
servers:
- url: http://localhost:{port}
  description: Локальный сервер разработки
  variables:
    port:
      default: 5100
      description: Порт
components:
  schemas:
    auth:
      type: object
      properties:
        email:
          type: string
          description: Почта
          required: true
        password:
          type: string
          description: Пароль
          required: true
    registration:
      type: object
      properties:
        name:
          type: string
          description: Имя
          required: true
        email:
          type: string
          description: Почта
          required: true
        password:
          type: string
          description: Пароль
          required: true
  securitySchemes:
    Bearer:
      description: Токен пользователя
      type: apiKey
      name: Authorization
      bearerFormat: JWT
      in: header
    Refresh:
      description: Токен сброса
      type: apiKey
      name: X-Refresh-Token
      bearerFormat: JWT
      in: header
